#define ID_APP_ACCEL 1
#define ID_APP_VERSION_INFO 1
#define ID_APP_MENU 1

#define ID_POPUP_MENU_TAB 2
#define ID_POPUP_MENU_BOOKMARK 3
#define ID_POPUP_MENU_BOOKMARK_FOLDER 4
#define ID_POPUP_MENU_MANAGE_BOOKMARKS 5

// Icons
#define IDI_APP 1
#define IDI_NEW_TAB 3
#define IDI_NEW_TAB_DARK 4

// Bitmaps
#define IDB_TOOLBAR_NAV 1
#define IDB_TOOLBAR_NAV_DISABLED 2
#define IDB_TOOLBAR_NAV_DARK 3

#define IDB_TOOLBAR_TABS 4
#define IDB_TOOLBAR_TABS_DARK 5

#define IDB_OVERFLOW 6
#define IDB_OVERFLOW_DISABLED 7
#define IDB_OVERFLOW_DARK 8

#define IDB_TAB_CLOSE 9
#define IDB_FOLDER 10
#define IDB_BOOKMARKLET 11
#define IDB_BLANK 12
#define IDB_BOOKMARKS 13

// Menu: File
#define IDM_NEW_TAB 100
#define IDM_NEW_PRIVATE_TAB 101
#define IDM_OPEN 102
#define IDM_CLOSE_TAB 103
#define IDM_CLOSE_ALL_TABS 104
#define IDM_SAVE_PAGE 105
#define IDM_PRINT_TO_PDF 106
#define IDM_SAVE_AS_IMAGE 107
#define IDM_PRINT 108
#define IDM_EXIT 199

// Menu: View
#define IDM_TOGGLE_FULLSCREEN 200
#define IDM_ESCAPE_FULLSCREEN 201
#define IDM_THEME_AUTO 202
#define IDM_THEME_LIGHT 203
#define IDM_THEME_DARK 204
#define IDM_TOGGLE_VERTICAL_TABS 205
#define IDM_TOGGLE_BOOKMARKS 206
#define IDM_TOGGLE_STATUSBAR 207

// Menu: History
#define IDM_SHOW_HISTORY 300
#define IDM_CLEAR_CACHE 301
#define IDM_CLEAR_COOKIES 302
#define IDM_CLEAR_HISTORY 303
#define IDM_CLEAR_ALL 304

// Menu: Bookmarks
#define IDM_BOOKMARKS_MANAGE 400
#define IDM_BOOKMARKS_IMPORT 401
#define IDM_BOOKMARKS_EXPORT 402
#define IDM_BOOKMARKS_BAR 403

// Menu: Tools
#define IDM_DOWNLOADS 500
#define IDM_BROWSER_EXTENSIONS 501
#define IDM_DEV_TOOLS 502
#define IDM_TASK_MANAGER 503
#define IDM_SETTINGS 504

// Menu: Help
#define IDM_ABOUT 600
#define IDM_SYSTEM_INFO 601
#define IDM_CREDITS 602

#define IDM_ZOOM_RESET 650
#define IDM_BACKEND_DEV_TOOLS 651

// popup menus
#define IDM_BOOKMARK_OPEN_NEW_TAB 700
#define IDM_BOOKMARK_OPEN_NEW_PRIVATE_TAB 701
#define IDM_BOOKMARK_COPY 702
#define IDM_BOOKMARK_EDIT 703
#define IDM_BOOKMARK_DELETE 704

#define IDM_CLOSE_OTHER_TABS 800
#define IDM_DISCARD_TAB 801
#define IDM_DISCARD_OTHER_TABS 802
#define IDM_MUTE_TAB 803
#define IDM_KEEP_TAB_LOADED 804

// Toobar commands
#define CMD_NEW_TAB 1000

#define CMD_BACK 1001
#define CMD_FORWARD 1002
#define CMD_RELOAD 1003

#define CMD_SEP_ADDRESS 1004
#define CMD_RESIZER 1005
#define CMD_SEP_SEARCH 1006

#define CMD_BOOKMARK 1010
#define CMD_EXTENSIONS 1011
#define CMD_PYADDONS 1012

#define CMD_PYADDONS_FIRST 2000
#define CMD_HISTORY_FIRST 3000
#define CMD_BOOKMARKS_FIRST 4000

// Dialogs
#define IDD_EDIT_BOOKMARK 1
#define IDD_RENAME_BOOKMARK_FOLDER 2
#define IDC_EDT_NAME 101
#define IDC_EDT_URL 102
